# Generated by Django 2.2.12 on 2020-04-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puputextension', '0004_auto_20200410_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='streambodyentrypage',
            name='css',
            field=models.FileField(null=True, upload_to='css/puput/entry_page/'),
        ),
    ]
