# Generated by Django 2.2.12 on 2020-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puputextension', '0005_streambodyentrypage_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streambodyentrypage',
            name='css',
            field=models.FileField(blank=True, null=True, upload_to='css/puput/entry_page/'),
        ),
    ]
