# Generated by Django 2.2.12 on 2020-04-23 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0005_blogpage_main_color'),
        ('home', '0020_auto_20200423_0206'),
        ('puputextension', '0011_auto_20200423_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlogPage',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.BlogPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('puput.blogpage',),
            managers=[
                ('extra', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomBlogPageNavBarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('navbar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_custom_blog_pages', to='home.NavBarItem')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='navbar_items', to='puputextension.CustomBlogPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
