# Generated by Django 2.2.15 on 2020-09-05 15:58

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_tutorialindexpage_navbar_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('handle', models.CharField(max_length=250)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tutorial',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutorials', to='tutorials.Instructor'),
        ),
    ]
