# Generated by Django 3.0.4 on 2020-04-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200401_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.NavBarItem'),
        ),
    ]
