# Generated by Django 3.0.4 on 2020-04-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200401_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbaritem',
            name='parent',
        ),
    ]
