# Generated by Django 3.0.4 on 2020-04-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200402_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='HomeFormField',
        ),
    ]
