# Generated by Django 2.2.12 on 2020-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='css',
            field=models.FileField(null=True, upload_to='css/home/'),
        ),
    ]
