# Generated by Django 2.2.12 on 2020-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_homepage_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='css',
            field=models.FileField(blank=True, null=True, upload_to='css/home/'),
        ),
    ]
