# Generated by Django 2.2.12 on 2020-04-23 14:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200423_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, default='#', max_length=250)),
                ('text', models.CharField(blank=True, max_length=100)),
                ('alias', models.CharField(blank=True, max_length=250)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.TableOfContentItem')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageTableOfContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc', to='home.HomePage')),
                ('toc_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_home_pages', to='home.TableOfContentItem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
