# Generated by Django 2.2.12 on 2020-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homepagetableofcontentitem_tableofcontentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagetableofcontentitem',
            name='toc_item',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='TableOfContentItem',
        ),
    ]
