# Generated by Django 2.2.12 on 2020-04-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200423_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageTableOfContentItem',
        ),
    ]
