# Generated by Django 2.2.12 on 2020-04-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0002_auto_20200423_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='banner_colour',
            field=models.CharField(blank=True, help_text='Fill in a hex colour value', max_length=6, null=True),
        ),
    ]
