# Generated by Django 2.2.12 on 2020-04-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0004_auto_20200423_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitebranding',
            old_name='text_color',
            new_name='accent_2_color',
        ),
    ]
