# Generated by Django 2.2.12 on 2020-04-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0007_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='robots_txt',
            field=models.FileField(default='', upload_to='seo/'),
            preserve_default=False,
        ),
    ]
