# Generated by Django 2.2.12 on 2020-04-27 16:52

from django.db import migrations, models
import django.db.models.deletion
import wagtailschemaorg.registry


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('multisite', '0008_seosettings_robots_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address_country', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_region', models.CharField(max_length=100)),
                ('address_postal_code', models.CharField(max_length=50)),
                ('address_street', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('twitter_handle', models.CharField(max_length=15)),
                ('facebook_url', models.URLField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailschemaorg.registry.SiteThingLD, models.Model),
        ),
    ]
