# Generated by Django 2.2.12 on 2020-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0009_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
