# Generated by Django 2.2.12 on 2020-04-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0010_organisation_facebook_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='twitter_handle',
            field=models.CharField(max_length=50),
        ),
    ]
