# Generated by Django 2.2.12 on 2020-04-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0012_organisation_facebook_pixel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='facebook_app_id',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='facebook_pixel_id',
        ),
        migrations.AddField(
            model_name='seosettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
