# Generated by Django 2.2.12 on 2020-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0013_auto_20200428_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosettings',
            name='append_brand_name_in_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seosettings',
            name='brand_name_in_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
