# Generated by Django 2.2.12 on 2020-04-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0014_auto_20200428_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
