# Generated by Django 2.2.12 on 2020-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0015_organisation_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
