# Generated by Django 2.2.13 on 2020-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisite', '0016_auto_20200429_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
